services:

  app:

    build: .

    container_name: linkverse-api

    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      - postgres

    volumes:
      - .:/app
      - /app/node_modules

  postgres:

    image: postgres:17

    container_name: linkverse-db

    restart: unless-stopped

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

      POSTGRES_DB: linkverse

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:

  postgres_data: